### ISSUE TITLE
Add unit test for account repository

### ISSUE THREAD

**Issue by kdhrubo** [kdhrubo/crx#264]
Add unit test for account repository

Please refer to the lead unit test setup. This should be exactly similar.

**Comment by Rajiv-mar121** [comment]
Ok Sure Dhrubo. Will try tonight.

Rajiv

On 22 Mar 2017 01:57, "Dhrubojyoti Kayal" <notifications@github.com> wrote:

Add unit test for account repository

Please refer to the lead unit test setup. This should be exactly similar.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kdhrubo/crx/issues/264>, or mute the thread

**Comment by Rajiv-mar121** [comment]
Code pushed
Branch : 264_account_test
